export default function HomePage() {
  return (
    <div className="container mx-auto px-4 py-8">
      <header className="text-center mb-12">
        <h1 className="text-5xl font-bold text-gray-800 mb-4">
          AI Report Studio
        </h1>
        <p className="text-xl text-gray-600">
          Transform your data into insightful narrative reports with the power of AI.
        </p>
      </header>

      <main>
        <section className="text-center mb-12">
          <h2 className="text-3xl font-semibold text-gray-700 mb-6">
            Effortless Data Analysis
          </h2>
          <p className="text-lg text-gray-500 max-w-3xl mx-auto">
            Upload your CSV or JSON files and let our AI generate comprehensive narrative reports, highlighting key insights and trends.
          </p>
        </section>

        <section className="text-center mb-12">
          <h2 className="text-3xl font-semibold text-gray-700 mb-6">
            Key Features
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="p-6 border rounded-lg shadow-sm">
              <h3 className="text-xl font-medium text-gray-700 mb-3">
                Data Upload
              </h3>
              <p className="text-gray-500">
                Easily upload your datasets in CSV or JSON format.
              </p>
            </div>
            <div className="p-6 border rounded-lg shadow-sm">
              <h3 className="text-xl font-medium text-gray-700 mb-3">
                AI-Powered Narratives
              </h3>
              <p className="text-gray-500">
                Get human-readable reports generated by AI from your data facts.
              </p>
            </div>
            <div className="p-6 border rounded-lg shadow-sm">
              <h3 className="text-xl font-medium text-gray-700 mb-3">
                Export Options
              </h3>
              <p className="text-gray-500">
                Export your reports in Markdown, HTML, or PDF formats.
              </p>
            </div>
          </div>
        </section>

        <section className="text-center">
          <h2 className="text-3xl font-semibold text-gray-700 mb-6">
            Get Started
          </h2>
          <p className="text-lg text-gray-500 mb-8 max-w-2xl mx-auto">
            Ready to unlock the insights hidden in your data? Upload your file and start generating reports today.
          </p>
          <button className="bg-blue-600 hover:bg-blue-700 text-white font-bold py-3 px-8 rounded-lg shadow-md transition duration-300">
            Upload Your Data
          </button>
        </section>
      </main>

      <footer className="text-center mt-16 pt-8 border-t border-gray-200">
        <p className="text-gray-500 text-sm">
          &copy; {new Date().getFullYear()} AI Report Studio. All rights reserved.
        </p>
      </footer>
    </div>
  )
}
